const teamActions = {
  addUser: { type: 'ADD_USER' },
  signIn: { type: 'SIGNIN_USER' },
  signOut: { type: 'SIGN_OUT' },
  logUser: { type: 'LOG_USER' },
  logError: { type: 'LOG_ERROR' },
  postArticle: { type: 'POST_ARTICLE' },
  postGIF: { type: 'POST_GIF' },
  getFeed: { type: 'GET_FEED' },
  deletePost: { type: 'DELETE_POST' },
  flagPost: { type: 'FLAG_POST' },
  likePost: { type: 'LIKE_POST' },
  editPost: { type: 'EDIT_POST' },
  getUser: { type: 'GET_USER' },
  updateArticle: { type: 'UPDATE_ARTICLE' },
  newUserSuccess: { type: 'NEWUSER_SUCCESS' },
  newUserFailure: { type: 'NEWUSER_FAILURE' },
  signInSuccess: { type: 'SIGNIN_SUCCESS' },
  signInFailure: { type: 'SIGNIN_FAILURE' },
  newArticleSuccess: { type: 'NEW_ARTICLE_SUCCESS' },
  newArticleFailure: { type: 'NEW_ARTICLE_FAILURE' },
  newGIFSuccess: { type: 'NEW_GIF_SUCCESS' },
  newGIFFailure: { type: 'NEW_GIF_FAILURE' },
  feedSuccess: { type: 'FEED_SUCCESS' },
  feedFailure: { type: 'FEED_FAILURE' },
  deletePostSuccess: { type: 'DELETE_SUCCESS' },
  deletePostFailure: { type: 'DELETE_FAILURE' },
  flagPostSuccess: { type: 'FLAG_SUCCESS' },
  flagPostFailure: { type: 'FLAG_FAILURE' },
  likePostSuccess: { type: 'LIKE_SUCCESS' },
  likePostFailure: { type: 'LIKE_FAILURE' },
  getUserSuccess: { type: 'GET_USER_SUCCESS' },
  getUserFailure: { type: 'GET_USER_FAILURE' },
};

export default teamActions;
